"""Generate ``data/disclaimer.md`` from the code constants.

The UI, the CLI and this file all render ``DISCLAIMER`` from
:mod:`src.rag.prompts`. Writing the text out by hand in three places is how a
submitted document and a running demo end up saying different things, so this
file is generated and the short string is read straight out of the constant.

Run after changing a prompt constant::

    .venv/bin/python scripts/build_disclaimer.py
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.config import CONFIG  # noqa: E402
from src.rag.prompts import ADVICE_REFUSAL, DISCLAIMER, EDU_LINK, PII_REFUSAL  # noqa: E402

LONG_VERSION = (
    "This assistant answers factual questions about five HDFC Mutual Fund schemes using only public "
    "scheme pages. Every answer is limited to three sentences and cites a single source link so you can "
    "check it yourself. It does not recommend buying, selling or holding any fund, does not assess "
    "whether a scheme is suitable for you, and does not forecast or compare returns. Figures are "
    "reproduced from the source page as captured on the date shown and may since have changed, so "
    "confirm anything that matters against the live page or with a registered mutual fund advisor."
)

TEMPLATE = """# Disclaimer

Generated by `scripts/build_disclaimer.py` — do not edit by hand.
Source of truth: `src/rag/prompts.py`.

## UI string (exact)

This is the literal value of `DISCLAIMER`, and what the UI renders in the main
area, the sidebar and the footer:

> {disclaimer}

## Long version (README and submission text)

{long}

## Other fixed strings

| Constant | Value | Used for |
|---|---|---|
| `ADVICE_REFUSAL` | {advice} | returned when a question asks for a recommendation |
| `PII_REFUSAL` | {pii} | returned before retrieval, when a PAN or email is detected |
| `EDU_LINK` | {edu} | investor-education link attached to the advice refusal |

The advice refusal must be ≤3 sentences and carry `EDU_LINK`; the PII refusal
must not echo the detected value back to the user or persist it anywhere.
"""


def main() -> int:
    body = TEMPLATE.format(
        disclaimer=DISCLAIMER,
        long=LONG_VERSION,
        advice=ADVICE_REFUSAL,
        pii=PII_REFUSAL,
        edu=EDU_LINK,
    )
    out = Path(CONFIG.documents_dir).parent / "disclaimer.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(body, encoding="utf-8")
    print(f"wrote {out} ({len(body)} bytes)")
    print(f"  DISCLAIMER matches src/rag/prompts.py: {DISCLAIMER in body}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
