"""Generate ``data/sample_qa.md`` by actually running the chain.

Every answer in that file is produced by calling the real pipeline, not written
by hand. That matters more than it sounds: a sample Q&A transcribed from memory
is exactly the kind of evidence Phase 6 exists to prevent, and a fabricated
"assistant answer" is worse than a blank cell.

The file is honest about what it could not produce. Three of the five rows are
factual answers, which require a key for the configured provider (``GROQ_API_KEY``). Without a key the chain
returns ``NO_MATCH`` by design, so rather than printing that as though it were
an answer, the row is marked PENDING and the retrieved fact it must state is
quoted underneath -- which is checkable today.

The advice-refusal and out-of-corpus rows need no key: the PII/advice guards
and the empty-hit path both return before generation is reached, so those two
answers are captured verbatim.

Run::

    .venv/bin/python scripts/build_sample_qa.py
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.config import CONFIG  # noqa: E402
from src.ingest.sources import load_sources  # noqa: E402
from src.rag.chain import answer  # noqa: E402
from src.rag.prompts import EDU_LINK  # noqa: E402
from src.rag.retriever import Retriever  # noqa: E402

# 3 factual, 1 advice refusal, 1 out-of-corpus, per implementation.md 6.2.
ROWS = [
    {"kind": "factual", "fact": "expense ratio", "query": "What is the expense ratio of HDFC Large Cap Fund?"},
    {"kind": "factual", "fact": "lock-in", "query": "What is the lock-in period for HDFC ELSS Tax Saver Fund?"},
    {"kind": "factual", "fact": "minimum sip", "query": "What is the minimum SIP amount for HDFC Flexi Cap Fund?"},
    {"kind": "advice", "fact": None, "query": "Should I buy HDFC Small Cap Fund?"},
    {"kind": "out-of-corpus", "fact": None, "query": "What is HDFC Bank's FD interest rate?"},
]

NO_CHUNK = "— no chunk cleared both gates —"
NOT_RETRIEVED = "n/a — refused before retrieval (PII/advice guard, or no chunk passed both gates)"

# Which fact row evidences each query. Matching on a generic list made a
# lock-in question quote "Expense ratio | 1.21%", because "expense ratio" came
# first -- the evidence column was confidently evidencing the wrong fact.
FACT_FOR_KIND = {
    "expense ratio": "expense ratio",
    "lock-in": "lock-in",
    "minimum sip": "minimum sip",
    "fund size": "fund size",
}


def _url_for(query: str, retriever: Retriever) -> str:
    """Source link for the top chunk, so the row cites what was retrieved."""
    hits = retriever.search(query)
    return hits[0].chunk.source_url if hits else ""


def _evidence(query: str, retriever: Retriever, want: str) -> tuple[str, float | None, str]:
    """The fact row this query is actually about, plus score and URL.

    ``want`` is the fact label to look for, not a generic scan: the retrieved
    chunk holds several "label | value" rows and only one of them answers the
    question.
    """
    needle = FACT_FOR_KIND.get(want, want)
    fallback = None
    for hit in retriever.search(query):
        for line in hit.chunk.text.splitlines():
            if needle in line.lower():
                return line.strip(), hit.score, hit.chunk.source_url
        if fallback is None:
            fallback = (f"(no {needle!r} row; chunk section: {hit.chunk.section})", hit.score, hit.chunk.source_url)
    if fallback:
        return fallback
    return "— no chunk cleared both gates —", None, ""


def build() -> str:
    sources = {s.scheme_key: s for s in load_sources()}
    retriever = Retriever()
    has_key = bool(CONFIG.llm_api_key)

    lines = [
        "# Sample Q&A",
        "",
        "Generated by `scripts/build_sample_qa.py` — do not edit by hand. Every answer below was",
        "produced by running the real chain (`src/rag/chain.py`), not transcribed.",
        "",
        f"- Corpus: {len(sources)} schemes, ingested into `{CONFIG.collection_name}`",
        f"- provider: `{CONFIG.llm_provider}` | model: `{CONFIG.llm_model}`",
        f"- `{CONFIG.llm_key_env_var}`: **{'present' if has_key else 'not set'}**",
    ]
    if not has_key:
        lines += [
            "",
            "> **The three factual rows are PENDING.** Without a key the chain returns `NO_MATCH` by",
            "> design, so no generated answer can be recorded yet. The *Evidence* column quotes the",
            "> retrieved fact each answer must state, which is verifiable today. Re-run this script",
            "> after adding a key to fill them in.",
        ]
    lines += [
        "",
        "## Answers",
        "",
        "| # | Query | Assistant answer | Source link | Verified |",
        "|---|---|---|---|---|",
    ]

    captured = 0
    evidence_rows = []
    for i, row in enumerate(ROWS, start=1):
        query = row["query"]
        result = answer(query)
        if row["fact"]:
            evidence, score, url = _evidence(query, retriever, row["fact"])
        else:
            # Refusal paths never reach retrieval, so "no chunk cleared the
            # gates" would be a false statement about why they were refused.
            evidence, score, url = NOT_RETRIEVED, None, ""
        if row["kind"] == "advice":
            url = EDU_LINK  # a refusal cites the investor-charter link, not a fund page

        is_refusal_path = row["kind"] in {"advice", "out-of-corpus"}
        if is_refusal_path or has_key:
            answer_cell = result.text.replace("|", "\\|").replace("\n", " ")
            captured += 1
        else:
            answer_cell = f"**PENDING** — no `{CONFIG.llm_key_env_var}`"

        link = f"[{url or '—'}]({url})" if url else "—"
        verified = "2026-09-27" if (is_refusal_path or has_key) else "—"
        lines.append(f"| {i} | {query} | {answer_cell} | {link} | {verified} |")
        evidence_rows.append((i, row, result, evidence, score))

    lines += ["", "## Row evidence", ""]
    for i, row, result, evidence, score in evidence_rows:
        lines += [
            f"### Row {i} — {row['kind']}",
            "",
            f"- Retriever score: **{'n/a (refused before retrieval)' if score is None else round(score, 3)}**",
            f"- Chunk fact: `{evidence}`",
            f"- Refusal kind: `{result.refusal_kind}`",
            f"- Citation URL emitted by chain: `{result.citation_url or '—'}`",
            "",
        ]

    lines += [
        "",
        "## Verification note",
        "",
        "The `Verified` column is a **placeholder for a human check**, not a claim. Per",
        "`implementation.md` §6.1, A7 requires opening each cited URL and confirming the figure by",
        "hand. That has not been done, and an automated run cannot substitute for it.",
        "",
        "What *is* machine-checked today:",
        "",
        "```bash",
        ".venv/bin/python -m evals.integrity     # corpus vs the page's own values",
 ".venv/bin/python scripts/eval_retrieval.py  # retrieval + separation + integrity",
        "```",
        "",
        f"Capture mode: {captured}/{len(ROWS)} rows have a verbatim captured answer.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    out = Path(CONFIG.documents_dir).parent / "sample_qa.md"
    body = build()
    out.write_text(body, encoding="utf-8")
    print(f"wrote {out} ({len(body)} bytes)")
    has_key = bool(CONFIG.llm_api_key)
    if has_key:
        print(f"  {CONFIG.llm_key_env_var}: present ({CONFIG.llm_provider} / {CONFIG.llm_model})")
    else:
        print(f"  {CONFIG.llm_key_env_var}: NOT SET -> 3 factual rows marked PENDING")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
